### ISSUE TITLE
[feature] Add multilang support

### ISSUE THREAD

**Issue by wopox1337** [SmileYzn/PugMod-AMXX#2]
Need to add clients (not server) multilang support.

**Comment by wopox1337** [comment]
as example code for global created ML menus (amxx 1.10)
```#include <amxmodx>

public plugin_init() {
    register_dictionary("languages.txt");

    BuildMenu();

    register_clcmd("radio1", "CMD");
}

new g_iMenu;
BuildMenu() {
    g_iMenu = menu_create("LANG_NAME", "menu_Handler", .ml = true);

    menu_additem(g_iMenu, "LANG_NAME", "1");
    menu_additem(g_iMenu, "LANG_NAME_NATIVE", "1");
}

public CMD(id) {
    menu_display(id, g_iMenu);

    return PLUGIN_HANDLED;
}


public menu_Handler(id, menu, item) {
    client_print(0, print_chat, "id:%i, menu:%i, key:%i", id, menu, item);

    if (item < 0)
        return PLUGIN_HANDLED;
    

    return PLUGIN_HANDLED;
}
```

it will be dependencies for client `setinfo lang` option

**Comment by SmileYzn** [comment]
I have created the mod to have this design: Server side translations only, since pug do not need any external plugins to run, even amxx plugins is not needed. You can create and change the mod, plugin is free.

Also 100% of menus is already translated, i know in some country the players need to choose a different language in mod, i still creating a best solution to this

**Comment by wopox1337** [comment]
I consider it necessary to support multiple client languages. Since several players from different countries can be on the same server. For example: if I have a server that is located in a location that is acceptable by ping for several countries.
