### ISSUE TITLE
Overtime not working as expected

### ISSUE THREAD

**Issue by ghost** [SmileYzn/PugMod-AMXX#55]
Overtime is not working as expected,
Example: 4 rounds of total 6 (3 each side) are won by team X and the match is not over.
Example2: Match should over at score: 17-19, but the teams keep swaping.
Overtime should work like this: Total 6 rounds (3 each side) and which team gets 4 rounds is the winner.

Little correction: After starting Overtime the teams should remain the same, not swapped.

Thank you for your time.

**Comment by SmileYzn** [comment]
Thanks for reporting it. Probably i will fix this on RePugMod for Metamod...

Released here: https://github.com/SmileYzn/RePugMod

I did not have sure if i will continue to work with amxmodx, updates are slow

**Comment by ghost** [comment]
The Amxmodx is easy and fast to work with for most people.
It is a good idea for metamod plugin - something different, which is nice, but personally for me it is better to fork ReGameDLL and code it there instead of metamod plugin.

I won't be much performance difference: metamod>amxx>plugins.. 
metamod>repugmode

I think you will loose time only. 

Anyway, thanks for the answer and your time.

**Comment by SmileYzn** [comment]
Losing time?

You can still use amxmodx while use RePugMod, also fork ReGameDLL_CS for what? Since whole API is already available to code for it.

If i fork ReGameDLL_CS how i can use other metamod plugins or amxmodx itself on custom ReGameDLL bro?

This do not make sense, to maintain a PugMod on amxmodx since ReGameDLL provide a api to work with it.
